#!/bin/bash

export PACKAGE_CORE_NAME="chatgpt-for-chatbot-wechat"
export PACKAGE_CORE_VERSION=v1.2.2
export PACKAGE_CORE_GIT_REPOSITORY="https://github.com/go-zoox/chatgpt-for-chatbot-wechat"
export PACKAGE_CORE_RELEASE_DOWNLOAD="${PACKAGE_CORE_GIT_REPOSITORY}/releases/download"
